### PR TITLE
Add namespace exclusion options

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes https://github.com/ProfessionalWiki/Network/issues/10

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@krabina this excludes talk pages, User, File and Help by default. Makes sense?

**Comment by krabina** [comment]
In my case User and File should be enabled, Help and Category should be excluded. But being configurable is ideal!

**Comment by JeroenDeDauw** [comment]
@kghbln which namespaces do you think should be excluded by default?

**Comment by JeroenDeDauw** [comment]
> Category should be excluded

@krabina putting a page in a category does not cause the category to show up in the network. It only does if you make an actual link to the category. So should it really be excluded for your use case?

**Comment by kghbln** [comment]
> which namespaces do you think should be excluded by default?

All namespaces that are not defined as content namespaces excluding file and category.

**Comment by JeroenDeDauw** [comment]
What namespaces are that?

**Comment by kghbln** [comment]
Main per https://www.mediawiki.org/wiki/Manual:$wgContentNamespaces Usually this is the parameter where you add your custom namespaces.

**Comment by JeroenDeDauw** [comment]
Yes. But what concrete namespaces to exclude by default? I want a list, not a parameter. As far as I know I cannot use a parameter as default when using the `extension.json` stuff.

**Comment by kghbln** [comment]
2, 4, 8, 10, 12 :)

**Pull request merged**
